---
- name: Testing andrewrothstein.kubevirt
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'virtctl version -v'
      ansible.builtin.command: /usr/local/bin/virtctl version -c
      changed_when: false
      register: kubevirt_test_output
    - name: Output from 'virtctl version -c'
      ansible.builtin.debug:
        msg: '{{ kubevirt_test_output.stdout }}'
