---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/virtctl version -c
    register: kubevirt_test_output
  - name: virtctl version -c
    debug:
      msg: '{{ kubevirt_test_output.stdout }}'
